-- dim_product: the bank's product master (static reference data defined in gold - no source system lands one)
-- covering every product name the silver feeds use; the covers_silver_product_names check enforces that.
WITH p (business_line, product_family, product_name, product_type, product_description) AS (
  VALUES
  ('Lending', 'Corporate Lending', 'Term Loan', 'Core product', 'Committed amortising or bullet term loan.'),
  ('Lending', 'Corporate Lending', 'Revolving Credit Facility', 'Core product', 'Committed revolving line drawn and repaid at will (RCF).'),
  ('Lending', 'Corporate Lending', 'Bilateral Loan', 'Core product', 'Loan agreed directly between SMBC and the client.'),
  ('Lending', 'Corporate Lending', 'Syndicated Loan', 'Core product', 'Loan shared with other lenders under one agreement.'),
  ('Lending', 'Corporate Lending', 'Overdraft', 'Core product', 'Uncommitted overdraft on a current account.'),
  ('Lending', 'Structured Lending', 'Project Finance', 'Core product', 'Non-recourse financing of a project against its cash flows.'),
  ('Lending', 'Structured Lending', 'Acquisition Finance', 'Core product', 'Financing for an acquisition or leveraged buy-out.'),
  ('Lending', 'Structured Lending', 'Asset Finance', 'Core product', 'Financing secured on aircraft, vessels or equipment.'),
  ('Transaction Banking', 'Cash', 'Current Account', 'Core product', 'Operating current account (CASA).'),
  ('Transaction Banking', 'Cash', 'Savings Account', 'Core product', 'Interest-bearing call / savings account (CASA).'),
  ('Transaction Banking', 'Cash', 'Correspondent Account', 'Core product', 'Nostro / vostro account for financial-institution clients.'),
  ('Transaction Banking', 'Cash', 'Notional Pooling', 'Core product', 'Liquidity structure offsetting balances without moving funds.'),
  ('Transaction Banking', 'Cash', 'Physical Pooling', 'Core product', 'Liquidity structure concentrating balances into a header account.'),
  ('Transaction Banking', 'Cash', 'Sweep', 'Core product', 'Automatic target-balance sweeps between accounts.'),
  ('Transaction Banking', 'Cash', 'Interest Optimisation', 'Core product', 'Interest enhancement across the group balances without pooling.'),
  ('Transaction Banking', 'Cash', 'Cash Management Mandate', 'CRM sales product', 'Mandate for operating accounts, payments and collections.'),
  ('Transaction Banking', 'Cash', 'Cash Pooling', 'CRM sales product', 'Sale of a notional or physical cash-pooling structure.'),
  ('Transaction Banking', 'Liquidity', 'Time Deposit', 'Core product', 'Fixed-term deposit (TD).'),
  ('Transaction Banking', 'Liquidity', 'Money Market Deposit', 'Core product', 'Short-term money-market deposit.'),
  ('Transaction Banking', 'Liquidity', 'Investment Account', 'Core product', 'Account for surplus-cash investment products.'),
  ('Transaction Banking', 'Payments', 'Domestic Payments', 'Core product', 'Domestic payments (RTGS, ACH, FAST).'),
  ('Transaction Banking', 'Payments', 'Cross-Border Payments', 'Core product', 'Cross-border payments (SWIFT MT / ISO 20022).'),
  ('Transaction Banking', 'Payments', 'Host-to-Host', 'Core product', 'File-based host-to-host connectivity for payments.'),
  ('Transaction Banking', 'Payments', 'Payments API', 'Core product', 'API connectivity for payments and statements.'),
  ('Transaction Banking', 'Trade Finance', 'Import LC', 'Core product', 'Import letter of credit issued for the client.'),
  ('Transaction Banking', 'Trade Finance', 'Export LC', 'Core product', 'Export letter of credit advised / confirmed for the client.'),
  ('Transaction Banking', 'Trade Finance', 'Guarantee / SBLC', 'Core product', 'Bank guarantee or standby letter of credit.'),
  ('Transaction Banking', 'Trade Finance', 'Documentary Collection', 'Core product', 'Collection of trade documents against payment or acceptance.'),
  ('Transaction Banking', 'Trade Finance', 'Trade Loan', 'Core product', 'Short-term loan financing a trade transaction.'),
  ('Transaction Banking', 'Trade Finance', 'Receivables Purchase', 'Core product', 'Purchase of trade receivables from the client.'),
  ('Transaction Banking', 'Trade Finance', 'Trade Finance Line', 'CRM sales product', 'Trade facility covering LCs, guarantees and trade loans.'),
  ('Transaction Banking', 'Supply Chain Finance', 'Payables Finance', 'Core product', 'Buyer-led SCF programme financing approved supplier invoices.'),
  ('Transaction Banking', 'Supply Chain Finance', 'Receivables Finance', 'Core product', 'Seller-led SCF programme financing receivables.'),
  ('Transaction Banking', 'Supply Chain Finance', 'Supply Chain Finance', 'CRM sales product', 'Sale of a supply chain finance programme to an anchor buyer.'),
  ('Markets', 'FX', 'FX Spot', 'Core product', 'Foreign-exchange spot deal.'),
  ('Markets', 'FX', 'FX Forward', 'Core product', 'Foreign-exchange forward deal.'),
  ('Markets', 'FX', 'FX Swap', 'Core product', 'Foreign-exchange swap.'),
  ('Markets', 'FX', 'FX Forward Programme', 'CRM sales product', 'Rolling FX hedging programme.'),
  ('Markets', 'Rates', 'Interest Rate Swap', 'Core product', 'Interest-rate swap.'),
  ('Markets', 'Rates', 'Cap/Floor', 'Core product', 'Interest-rate cap or floor.'),
  ('Markets', 'Rates', 'Interest Rate Hedge', 'CRM sales product', 'Interest-rate hedging solution for a loan book.'),
  ('Sustainable Finance', 'Sustainable Finance', 'Green Loan', 'Core product', 'Loan financing eligible green projects.'),
  ('Sustainable Finance', 'Sustainable Finance', 'Sustainability-Linked Loan', 'Core product', 'Loan with margin linked to sustainability KPIs (SLL).')
)
SELECT
  concat('PRD-', upper(regexp_replace(product_name, '[^A-Za-z0-9]+', '-')))                   AS product_id,
  product_name,
  product_family,
  business_line,
  product_type,
  (business_line IN ('Lending', 'Sustainable Finance') OR product_family IN ('Trade Finance', 'Supply Chain Finance'))
    AND product_name <> 'Documentary Collection'                                                AS is_credit_product,
  product_name IN ('Current Account', 'Savings Account', 'Correspondent Account', 'Time Deposit',
                   'Money Market Deposit', 'Investment Account')                               AS is_deposit_product,
  business_line = 'Transaction Banking'                                                        AS is_tb_product,
  business_line = 'Sustainable Finance'                                                        AS is_sustainable,
  product_description
FROM p
